# Generated by Django 2.0.6 on 2018-07-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=2048)),
                ('true_answer', models.CharField(max_length=1048)),
                ('wrong_answer1', models.CharField(max_length=1048)),
                ('wrong_answer2', models.CharField(max_length=1048)),
                ('wrong_answer3', models.CharField(max_length=1048)),
                ('have_code', models.BooleanField(default=False)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='categories.Category')),
            ],
            options={
                'ordering': ('create_time',),
            },
        ),
    ]
