# Generated by Django 2.0.6 on 2018-07-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
